[project]
name = "torchattack"
version = "0.2.1"
description = "A set of adversarial attacks implemented in PyTorch"
authors = [{ name = "spencerwooo", email = "spencer.woo@outlook.com" }]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }
dependencies = [
    "torch>=1.13.0",
    "torchvision>=0.14.0",
    "numpy>=1.24.2",
    "scipy>=1.10.1",
    "rich>=13.3.5",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 88
select = ["E", "F", "I", "N", "B", "SIM"]
ignore = ["E501"]

[tool.ruff.format]
# Use single quotes rather than double quotes.
quote-style = "single"

[tool.mypy]
disallow_any_unimported = true
no_implicit_optional = true
check_untyped_defs = true
ignore_missing_imports = true  # Used as torchvision does not ship type hints
# disallow_untyped_defs = true
# warn_return_any = true
