name: lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      # - uses: psf/black@stable
      - name: Ruff format
        uses: chartboost/ruff-action@v1
        with:
          args: format --check
      - name: Ruff lint
        uses: chartboost/ruff-action@v1
      - name: Mypy
        run: |
          pip install -r requirements.txt
          pip install mypy
          mypy src/
